# Dependencies
# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

sidebar-links:
  email: mail@spartha.org
  twitter: sp4rth4
  linkedin: parthasusarla
  github: ajaysusarla


# Permalinks
permalink:        pretty

# Setup
title:            Partha Susarla
tagline:          '!(just another brick in the wall)'
description:      '!(just another brick in the wall)'
url:              https://spartha.org
baseurl:          /

author:
  name:           'Partha'
  url:            https://twitter.com/

paginate:         5

# Set the Sass partials directory, as we're using @imports
#sass:
#  style: :expanded # You might prefer to minify using :compressed


# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - jekyll-theme-LICENSE.md
  - CNAME

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ajaysusarla

gems:
  - jekyll-paginate
  - jekyll-gist
